import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import React, { PropsWithChildren } from "react"
import Header from "@/app/_shared/components/header"
import AuthProvider from "@/app/_shared/contexts/auth.provider"
import "primereact/resources/themes/soho-dark/theme.css"
import { PrimeReactProvider } from "primereact/api"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Time Tracker",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <PrimeReactProvider>
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </PrimeReactProvider>
      </body>
    </html>
  )
}
