import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import React, { PropsWithChildren } from "react"
import Header from "@/app/_shared/components/header"
import AuthProvider from "@/app/_shared/contexts/auth.provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Time Tracker",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
